name: Build Windows EXE

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Windows binaries
      run: |
        cd contrib/build-wine
        ./build.sh
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: electrum-windows-binaries
        path: contrib/build-wine/dist/*.exe
        retention-days: 30 